apiVersion: v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otus_homework_1p($|/)(.*)
            backend:
              serviceName: hello-service
              servicePort: 8000